swagger: "2.0"
info:
  description: "QIM - API"
  version: "1"
  title: "Swagger QIM"
schemes:
  - "https"
  - "http"
paths:
  /empresa/{empresa_id}/almoxarifado:
    options:
      x-swagger-router-controller: controller.almoxarifado
      operationId: options
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        200:
          description: Default response for CORS method
    get:
      x-swagger-router-controller: controller.almoxarifado
      operationId: search
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "query"
          name: "nome"
          required: false
          type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/almoxarifado"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    post:
      x-swagger-router-controller: controller.almoxarifado
      operationId: post
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/almoxarifado'
      responses:
        "201":
          description: "Criado"
          schema:
            $ref: '#/definitions/almoxarifado'
        "400":
          description: "Request Inválida"
        "401":
          description: "Não autorizado"

  /empresa/{empresa_id}/almoxarifado/{almoxarifado_id}:
    options:
      x-swagger-router-controller: controller.almoxarifado
      operationId: options_id
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "almoxarifado_id"
          required: true
          type: "string"
      summary: CORS suporte
      description: Habilita o CORS retornando os cabeçalhos corretos
      responses:
        200:
          description: Metodo generico para CORS
    get:
      x-swagger-router-controller: controller.almoxarifado
      operationId: get
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "almoxarifado_id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/almoxarifado"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    put:
      x-swagger-router-controller: controller.almoxarifado
      operationId: put
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "almoxarifado_id"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/almoxarifado"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/almoxarifado"
        "400":
          description: "Dados Inválidos"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    delete:
      x-swagger-router-controller: controller.almoxarifado
      operationId: delete
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "almoxarifado_id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Dados Inválidos"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
  /empresa/{empresa_id}/operador:
    options:
      x-swagger-router-controller: controller.operador
      operationId: options
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        200:
          description: Default response for CORS method
    get:
      x-swagger-router-controller: controller.operador
      operationId: search
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "query"
          name: "nome"
          required: false
          type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/operador"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    post:
      x-swagger-router-controller: controller.operador
      operationId: post
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/operador'
      responses:
        "201":
          description: "Criado"
          schema:
            $ref: '#/definitions/operador'
        "400":
          description: "Request Inválida"
        "401":
          description: "Não autorizado"

  /empresa/{empresa_id}/operador/{operador_id}:
    options:
      x-swagger-router-controller: controller.operador
      operationId: options_id
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "operador_id"
          required: true
          type: "string"
      summary: CORS suporte
      description: Habilita o CORS retornando os cabeçalhos corretos
      responses:
        200:
          description: Metodo generico para CORS
    get:
      x-swagger-router-controller: controller.operador
      operationId: get
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "operador_id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/operador"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    put:
      x-swagger-router-controller: controller.operador
      operationId: put
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "operador_id"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/operador"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/operador"
        "400":
          description: "Dados Inválidos"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    delete:
      x-swagger-router-controller: controller.operador
      operationId: delete
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "path"
          name: "operador_id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Dados Inválidos"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
  /empresa:
    options:
      x-swagger-router-controller: controller.empresa
      operationId: options
      produces:
        - "application/json"
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        200:
          description: Default response for CORS method
    get:
      x-swagger-router-controller: controller.empresa
      operationId: search
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "nome"
          required: false
          type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/empresa"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    post:
      x-swagger-router-controller: controller.empresa
      operationId: post
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/empresa'
      responses:
        "201":
          description: "Criado"
          schema:
            $ref: '#/definitions/empresa'
        "400":
          description: "Request Inválida"
        "401":
          description: "Não autorizado"

  /empresa/{empresa_id}:
    options:
      x-swagger-router-controller: controller.empresa
      operationId: options_id
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
      summary: CORS suporte
      description: Habilita o CORS retornando os cabeçalhos corretos
      responses:
        200:
          description: Metodo generico para CORS
    get:
      x-swagger-router-controller: controller.empresa
      operationId: get
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/empresa"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    put:
      x-swagger-router-controller: controller.empresa
      operationId: put
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/empresa"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/empresa"
        "400":
          description: "Dados Inválidos"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"
    delete:
      x-swagger-router-controller: controller.empresa
      operationId: delete
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "empresa_id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Dados Inválidos"
        "401":
          description: "Não autorizado"
        "404":
          description: "Não encontrado"

  /login:
    options:
      x-swagger-router-controller: controller.usuario
      operationId: options
      produces:
        - "application/json"
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        200:
          description: Default response for CORS method
    post:
      x-swagger-router-controller: controller.usuario
      operationId: login
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/login'
      responses:
        "200":
          description: "Autenticado"
        "400":
          description: "Request Inválida"
        "401":
          description: "Não autorizado"

definitions:
  almoxarifado:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
  empresa:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nomeUsuario:
        type: "string"
      lingua:
        type: "string"
      tipoArmazenagem:
        type: "string"
      aceiteTermosUso:
        type: "boolean"
      senha:
        type: "string"
  operador:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nomeUsuario:
        type: "string"
      acesso:
        type: "string"
      senha:
        type: "string"

  login:
    type: "object"
    properties:
      tipo:
        type: "string"
      senha:
        type: "string"
      nome_usuario:
        type: "string"